name: DarleneFarris.com
favicon: null
layout_spectrum: 0.5601504
typography_spectrum: 0.3603652
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#020202'
    - '#5d494b'
    - '#67768e'
    - '#89a9c7'
  brandStrength: 0
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
