collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9876477
  brandStrength: 0.1079484
  lightness: 0.3689581
  brandColors:
    - '#FFFFFF'
    - '#FBCDB5'
    - '#4B4B5C'
    - '#C6436E'
    - '#888892'
  rhythmicContrast: 0.1965525
typography_spectrum: 0.3603652
layout_spectrum: 0
name: DarleneFarris.com
