favicon: null
name: DarleneFarris.com
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.0625
  brandStrength: 0.1079484
  rhythmicContrast: 0.8845327
  brandColors:
    - '#FFFFFF'
    - '#FBCDB5'
    - '#4B4B5C'
    - '#C6436E'
    - '#888892'
  lightness: 0.25
typography_spectrum: 0.3603652
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5601504
analytics:
  twitter: null
  google: null
  facebook: null
